theme: jekyll-theme-minimal

title: LaboratorioDeProjetos3
description: Repositório da disciplina Laboratório de Projetos 3, 2019-02, Grupo B
logo: https://github.com/brunasqz/LaboratorioDeProjetos3/raw/master/docs/logo.jpg
show_downloads: false